# Numpy

In [1]:
import numpy as np

In [21]:
np.random.randn()

0.8747774905992417

In [5]:
np.arange(15)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [6]:
arr = np.array([3.7,-1.2,-2.6,0.5,12,9])

## Numpy array의 산술 연산

In [7]:
arr=np.array([
    [1.,2.,3.,],
    [4.,5.,6.]
])
arr

array([[1., 2., 3.],
       [4., 5., 6.]])

In [8]:
arr*arr

array([[ 1.,  4.,  9.],
       [16., 25., 36.]])

In [9]:
arr-arr

array([[0., 0., 0.],
       [0., 0., 0.]])

In [10]:
1/arr

array([[1.        , 0.5       , 0.33333333],
       [0.25      , 0.2       , 0.16666667]])

In [11]:
arr**0.5

array([[1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974]])

In [12]:
arr2=np.array([
    [0.,4.,1.,],
    [7.,2.,12.,]
])
arr2

array([[ 0.,  4.,  1.],
       [ 7.,  2., 12.]])

In [13]:
arr2>arr

array([[False,  True, False],
       [ True, False,  True]])

In [15]:
arr=np.arange(15)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [16]:
arr_slice=arr[5:8]
arr_slice

array([5, 6, 7])

In [17]:
# 복제본이 아니라 뷰여서. 원본에 교체된다!
#list의 슬라이싱에서의 할당(복제)과 다르다.
arr_slice[:]=64
arr

array([ 0,  1,  2,  3,  4, 64, 64, 64,  8,  9, 10, 11, 12, 13, 14])

## Boolean Indexing
색인을 위해서 요소의 개수와 동일한 블리언 배열을 받아서 True 요소만 반환한다.  
데이터의 필터링에 아주 많이 사용 되는 기법이다.

In [22]:
names=np.array(['Bob','Joe','Will','Bob','Will','Joe','Joe'])
data=np.random.randn(7,4)
names

array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'], dtype='<U4')

In [23]:
data

array([[ 1.309182  ,  0.92287792, -0.33515391, -0.80142147],
       [-0.44755927, -0.24163191,  1.42670573, -0.96057719],
       [-1.11790956, -0.05999465, -0.34585154,  0.40583293],
       [ 0.13901298, -1.09618895, -0.83046054, -0.09068012],
       [-0.22888279,  0.76648475,  0.06115607,  1.19986474],
       [ 1.32981574,  0.08333392,  1.14867783,  1.41595942],
       [ 1.56387151,  0.75437612,  0.47370349, -1.18843533]])

In [24]:
names=='Bob'

array([ True, False, False,  True, False, False, False])

In [25]:
data[names=='Bob']

array([[ 1.309182  ,  0.92287792, -0.33515391, -0.80142147],
       [ 0.13901298, -1.09618895, -0.83046054, -0.09068012]])

In [26]:
data[data<0]

array([-0.33515391, -0.80142147, -0.44755927, -0.24163191, -0.96057719,
       -1.11790956, -0.05999465, -0.34585154, -1.09618895, -0.83046054,
       -0.09068012, -0.22888279, -1.18843533])

## fancy indexing
참조하고자 하는 인덱스의 목록을 배열에 전달하면 인덱스가 일치하는 값만 선택된다.

In [27]:
arr=np.empty((8,4))
arr

array([[ 6.01347002e-154,  6.01347002e-154,  1.14156315e+243,
         6.22651684e+228],
       [ 6.01347002e-154,  6.01347002e-154,  1.75631032e-152,
         1.01301879e+242],
       [ 2.46003923e+198, -1.05695522e-310,  5.98186784e-154,
         6.01347002e-154],
       [ 4.70075024e+180,  2.91256665e-014,  6.19976710e+223,
         5.42786351e-109],
       [ 6.01347002e-154,  6.01347002e-154,  1.81667905e-152,
         5.03942792e+180],
       [ 2.52931895e-086,  4.72379997e-120,  1.92881348e-110,
         6.01347002e-154],
       [ 4.17309334e+199,  5.55603543e+180,  3.86930526e-144,
         2.78143447e+180],
       [ 1.27587194e-152,  8.01235034e+165,  7.87810646e-154,
        -1.10809529e-310]])

In [28]:
for i in range(8):
    arr[i]=i
arr

array([[0., 0., 0., 0.],
       [1., 1., 1., 1.],
       [2., 2., 2., 2.],
       [3., 3., 3., 3.],
       [4., 4., 4., 4.],
       [5., 5., 5., 5.],
       [6., 6., 6., 6.],
       [7., 7., 7., 7.]])

In [29]:
arr[[4,3,0,6]]

array([[4., 4., 4., 4.],
       [3., 3., 3., 3.],
       [0., 0., 0., 0.],
       [6., 6., 6., 6.]])

In [31]:
arr=np.arange(32).reshape((8,4))
arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23],
       [24, 25, 26, 27],
       [28, 29, 30, 31]])

In [32]:
#limit row and col
arr[[1,5,7,2],[0,3,1,2]]

array([ 4, 23, 29, 10])

In [33]:
#limit row
arr[[1,5,7,2,]]

array([[ 4,  5,  6,  7],
       [20, 21, 22, 23],
       [28, 29, 30, 31],
       [ 8,  9, 10, 11]])

In [34]:
#위와 같은데 순서 변경해서 가져오기
arr[[1,5,7,2,]][:,[0,3,1,2]]

array([[ 4,  7,  5,  6],
       [20, 23, 21, 22],
       [28, 31, 29, 30],
       [ 8, 11,  9, 10]])

## axis and transpose

In [35]:
arr=np.arange(15).reshape((3,5))
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [36]:
arr.T

array([[ 0,  5, 10],
       [ 1,  6, 11],
       [ 2,  7, 12],
       [ 3,  8, 13],
       [ 4,  9, 14]])

In [37]:
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [39]:
arr=np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [40]:
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ])

In [41]:
np.exp(arr)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03])

In [42]:
x=np.random.randn(8)
y=np.random.randn(8)

In [43]:
x

array([ 1.29071043, -1.28956855,  0.93976445, -0.69541759,  0.77771947,
       -0.45172486, -0.03953638,  0.28727533])

In [44]:
y

array([ 0.33212841, -0.45275115,  0.86458054, -0.77886943, -0.63490049,
        0.97057691, -0.60122184, -0.66946542])

In [46]:
np.maximum(x,y)

array([ 1.29071043, -0.45275115,  0.93976445, -0.69541759,  0.77771947,
        0.97057691, -0.03953638,  0.28727533])

In [47]:
arr=np.random.randn(7)*5
arr

array([ -3.61666152,  -2.11050003,   9.77129821,  -5.32752821,
        -1.20695928,   8.27100776, -10.71375926])

In [ ]:
remainder, whole_part = np.modf(arr)
remainder

In [52]:
samples=np.random.normal(size=(4,4))
samples

array([[ 0.86551753, -0.67733149, -0.44432575,  2.11034991],
       [ 0.76868595, -0.58447481,  1.0036673 , -1.56297181],
       [ 1.10703111,  0.11931327,  1.04049028,  1.74981403],
       [ 0.10461441, -2.00942209,  0.47424742, -0.47626423]])

In [53]:
np.random.seed(1234)

In [60]:
rng=np.random.RandomState(1234) #seed 정한 randomstate 객체
rng.randn(10)

array([ 0.47143516, -1.19097569,  1.43270697, -0.3126519 , -0.72058873,
        0.88716294,  0.85958841, -0.6365235 ,  0.01569637, -2.24268495])