# Practice

## #1. Linear Algebra

In [1]:
va=[2,2]; vb=[2,3]; vc=[3,5]

In [3]:
import numpy as np

In [8]:
vr = 5 * np.array(va)
print(vr)

[10 10]


In [23]:
print([  5 * e for e in va  ])

[10, 10]


In [10]:
vr = np.array(va) + np.array(vb) + np.array(vc)
print(vr)

[ 7 10]


In [24]:
print([  a+b+c for a,b,c in zip(va,vb,vc)  ])

[7, 10]


In [11]:
vr = 5 * (  np.array(va) + np.array(vb)  )
print(vr)

[20 25]


In [25]:
print([  5*(a+b) for a,b in zip(va,vb)  ])

[20, 25]


## #2. Matrix

In [12]:
ma=[[3,6], [4,5]]
mb=[[5,8], [6,7]]

In [14]:
mr = 10 * np.array(ma)
print(mr)

[[30 60]
 [40 50]]


In [29]:
# print([  10 * e for e in ma  ])
print([  [10 * c for c in r] for r in ma  ])

[[30, 60], [40, 50]]


In [15]:
mr = np.array(ma) + np.array(mb)
print(mr)

[[ 8 14]
 [10 12]]


In [32]:
# print([  [a+b for a,b in ra,rb] for ra,rb in zip(ma,mb)  ])
print([  [sum(j) for j in zip(*i)] for i in zip(ma,mb)  ])

[[8, 14], [10, 12]]


In [18]:
ma = [[3,6], [4,5]]

In [19]:
mr = np.array(ma).T
print(mr)

[[3 4]
 [6 5]]


In [20]:
mc = [[1,2,3], [4,5,6]]
md = [[1,4], [2,5], [3,6]]

In [21]:
np.array(mc) * np.array(md)

ValueError: operands could not be broadcast together with shapes (2,3) (3,2) 

In [22]:
np.dot(mc, md)

array([[14, 32],
       [32, 77]])