### 사이킷런을 이용하여 붓꽃(Iris) 데이터 품종 예측하기

#### 붓꽃 데이터 적재 및 파악

In [1]:
import sklearn
# 위 구문은 scikit-learn의 서브패키지들은 임포트 되지 않습니다. 
# 모든 서브패키지들을 한 번에 임포트하려면 "from sklearn import *"를 수행하시면 됩니다. 

In [2]:
print(sklearn.__version__)

0.21.1


In [3]:
from sklearn.datasets import load_iris
from sklearn.tree import DecisionTreeClassifier
from sklearn.model_selection import train_test_split

In [4]:
import pandas as pd

# 붓꽃 데이터 세트를 로딩합니다. 
iris = load_iris()


In [5]:
# iris dataset 확인

In [6]:
iris.keys()

dict_keys(['data', 'target', 'target_names', 'DESCR', 'feature_names', 'filename'])

In [7]:
# 특성 
iris.data

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1],
       [5.4, 3.7, 1.5, 0.2],
       [4.8, 3.4, 1.6, 0.2],
       [4.8, 3. , 1.4, 0.1],
       [4.3, 3. , 1.1, 0.1],
       [5.8, 4. , 1.2, 0.2],
       [5.7, 4.4, 1.5, 0.4],
       [5.4, 3.9, 1.3, 0.4],
       [5.1, 3.5, 1.4, 0.3],
       [5.7, 3.8, 1.7, 0.3],
       [5.1, 3.8, 1.5, 0.3],
       [5.4, 3.4, 1.7, 0.2],
       [5.1, 3.7, 1.5, 0.4],
       [4.6, 3.6, 1. , 0.2],
       [5.1, 3.3, 1.7, 0.5],
       [4.8, 3.4, 1.9, 0.2],
       [5. , 3. , 1.6, 0.2],
       [5. , 3.4, 1.6, 0.4],
       [5.2, 3.5, 1.5, 0.2],
       [5.2, 3.4, 1.4, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [5.4, 3.4, 1.5, 0.4],
       [5.2, 4.1, 1.5, 0.1],
       [5.5, 4.2, 1.4, 0.2],
       [4.9, 3

In [8]:
# target (종속변수) - 분류하고자 하는 레이블(0,1,2로 저장)
iris.target

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [9]:
# target의 이름들
iris.target_names

array(['setosa', 'versicolor', 'virginica'], dtype='<U10')

In [10]:
# IRIS 데이터에 대한 설명
iris.DESCR

'.. _iris_dataset:\n\nIris plants dataset\n--------------------\n\n**Data Set Characteristics:**\n\n    :Number of Instances: 150 (50 in each of three classes)\n    :Number of Attributes: 4 numeric, predictive attributes and the class\n    :Attribute Information:\n        - sepal length in cm\n        - sepal width in cm\n        - petal length in cm\n        - petal width in cm\n        - class:\n                - Iris-Setosa\n                - Iris-Versicolour\n                - Iris-Virginica\n                \n    :Summary Statistics:\n\n    ============== ==== ==== ======= ===== ====================\n                    Min  Max   Mean    SD   Class Correlation\n    ============== ==== ==== ======= ===== ====================\n    sepal length:   4.3  7.9   5.84   0.83    0.7826\n    sepal width:    2.0  4.4   3.05   0.43   -0.4194\n    petal length:   1.0  6.9   3.76   1.76    0.9490  (high!)\n    petal width:    0.1  2.5   1.20   0.76    0.9565  (high!)\n    ============== ==== =

In [11]:
# 특성들의 이름 (컬럼 이름)
iris.feature_names

['sepal length (cm)',
 'sepal width (cm)',
 'petal length (cm)',
 'petal width (cm)']

In [12]:
# iris 데이터 파일의 경로
iris.filename

'C:\\ProgramData\\Anaconda3\\lib\\site-packages\\sklearn\\datasets\\data\\iris.csv'

In [13]:
# iris.data는 Iris 데이터 세트에서 피처(feature)만으로 된 데이터를 numpy로 가지고 있습니다. 
iris_data = iris.data

# iris.target은 붓꽃 데이터 세트에서 레이블(결정 값) 데이터를 numpy로 가지고 있습니다. 
iris_label = iris.target
print('iris target값:', iris_label)
print('iris target명:', iris.target_names)

iris target값: [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 2 2 2 2 2 2 2 2 2 2 2
 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2
 2 2]
iris target명: ['setosa' 'versicolor' 'virginica']


In [14]:
# 붓꽃 데이터 세트를 자세히 보기 위해 DataFrame으로 변환합니다. 
iris_df = pd.DataFrame(data=iris_data, columns=iris.feature_names)
iris_df['label'] = iris.target
iris_df.head(3)

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
0                5.1               3.5                1.4               0.2   
1                4.9               3.0                1.4               0.2   
2                4.7               3.2                1.3               0.2   

   label  
0      0  
1      0  
2      0

#### 결정트리 분류 실습

In [15]:
# DecisionTreeClassifier 객체 생성 
dt_clf = DecisionTreeClassifier()

# 학습 수행 
dt_clf.fit(iris.data, iris.target)

# 모델 평가
dt_clf.score(iris.data, iris.target)

1.0

#### train_test_split() 함수를 활용하여 학습데이터와 테스트 데이터 분리 실습

In [16]:
# 학습(훈련) 데이터와 테스트 데이터로 분리 (기본값은 3:1로 나눔 = test_size = 0.25)
X_train, X_test, y_train, y_test = train_test_split(iris_data, iris_label, 
                                                    test_size=0.2, random_state = 100)

In [17]:
# DecisionTreeClassifier 객체 생성 
dt_clf = DecisionTreeClassifier()

# 학습 수행 
dt_clf.fit(X_train, y_train)

DecisionTreeClassifier(class_weight=None, criterion='gini', max_depth=None,
                       max_features=None, max_leaf_nodes=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, presort=False,
                       random_state=None, splitter='best')

In [18]:
dt_clf.predict([1,2,3,1])

ValueError: Expected 2D array, got 1D array instead:
array=[1. 2. 3. 1.].
Reshape your data either using array.reshape(-1, 1) if your data has a single feature or array.reshape(1, -1) if it contains a single sample.

In [69]:
# 학습이 완료된 DecisionTreeClassifier 객체에서 테스트 데이터 세트로 예측 수행. 
pred = dt_clf.predict(X_test)

In [70]:
from sklearn.metrics import accuracy_score
print('예측 정확도: {0:.4f}'.format(accuracy_score(y_test,pred)))

예측 정확도: 0.9667


In [71]:
dt_clf.score(X_test, y_test)

0.9666666666666667

#### 교차 검증을 활용하여 모델 성능 개선

In [148]:
from sklearn.model_selection import KFold
kfold = KFold(n_splits=5, shuffle = False) #shuffle의 기본값은 False
# dt_clf = DecisionTreeClassifier(random_state = 100) 
# 결정트리 알고리즘에서 과적합을 막기 위해 랜덤으로 결정하는 부분이 있어서, 실행할 때마다 결과가 달라짐.
# 만약 동일하게 하고 싶으면 random_state를 특정 값으로 설정

In [161]:
accuracies = []
for train_idx, test_idx in kfold.split(iris_data):
    X_train, X_test = iris_data[train_idx], iris_data[test_idx]
    y_train, y_test = iris_label[train_idx], iris_label[test_idx]
    #print(len(train_idx), len(test_idx)) # 훈련용데이터와 검증용 데이터의 크기 확인
    #print('검증데이터셋', test_idx) # shuffle 확인용 출력
    # print(pd.Series(y_train).value_counts()) # 데이터 분포 확인
    #학습 및 예측 
    dt_clf.fit(X_train , y_train)    
    print(dt_clf.score(X_test, y_test))
    accuracies.append(dt_clf.score(X_test, y_test))
print('정확도: ', pd.Series(accuracies).mean())
    

2    50
1    50
0    20
dtype: int64
1.0
2    50
1    40
0    30
dtype: int64
0.9666666666666667
2    50
0    50
1    20
dtype: int64
0.9
0    50
1    40
2    30
dtype: int64
0.9333333333333333
1    50
0    50
2    20
dtype: int64
0.7333333333333333
정확도:  0.9066666666666666


#### stratified K 폴드 교차검증 실습

In [156]:
from sklearn.model_selection import StratifiedKFold
skfold = StratifiedKFold(n_splits=5, shuffle = False) #shuffle의 기본값은 False
# dt_clf = DecisionTreeClassifier(random_state = 100) 
# 결정트리 알고리즘에서 과적합을 막기 위해 랜덤으로 결정하는 부분이 있어서, 실행할 때마다 결과가 달라짐.
# 만약 동일하게 하고 싶으면 random_state를 특정 값으로 설정

In [162]:
accuracies = []
# StratifiedKFold의 split( ) 호출시 반드시 레이블 데이터 셋도 추가 입력 필요  
for train_idx, test_idx in skfold.split(iris_data, iris_label):
    X_train, X_test = iris_data[train_idx], iris_data[test_idx]
    y_train, y_test = iris_label[train_idx], iris_label[test_idx]
    #print(len(train_idx), len(test_idx))
    #print('검증데이터셋', test_idx)
    #print(pd.Series(y_train).value_counts())
    #학습 및 예측 
    dt_clf.fit(X_train , y_train)    
    print(dt_clf.score(X_test, y_test))
    accuracies.append(dt_clf.score(X_test, y_test))
print('정확도: ', pd.Series(accuracies).mean())
    

2    40
1    40
0    40
dtype: int64
0.9666666666666667
2    40
1    40
0    40
dtype: int64
0.9666666666666667
2    40
1    40
0    40
dtype: int64
0.9
2    40
1    40
0    40
dtype: int64
0.9333333333333333
2    40
1    40
0    40
dtype: int64
1.0
정확도:  0.9533333333333334


#### 교차 검증을 보다 간편하게 : cross_val_score()

In [163]:
from sklearn.model_selection import cross_val_score, cross_validate

In [166]:
cross_val_score(dt_clf, iris_data, iris_label, cv = 5)

array([0.96666667, 0.96666667, 0.9       , 0.93333333, 1.        ])

In [169]:
cross_validate(dt_clf, iris_data, iris_label, cv = 5, return_train_score=True)

{'fit_time': array([0.00099683, 0.        , 0.        , 0.00099754, 0.        ]),
 'score_time': array([0., 0., 0., 0., 0.]),
 'test_score': array([0.96666667, 0.96666667, 0.9       , 0.93333333, 1.        ]),
 'train_score': array([1., 1., 1., 1., 1.])}

#### 하이퍼파라미터 튜닝 - GridSearchCV() 

In [171]:
from sklearn.model_selection import GridSearchCV


In [172]:
### parameter 들을 dictionary 형태로 설정
parameters = {'max_depth':[1,2,3], 'min_samples_split':[2,3]}

In [182]:
# param_grid의 하이퍼 파라미터들을 5개의 train, test set fold 로 나누어서 테스트 수행 설정.  
### refit=True 가 default 임. True이면 가장 좋은 파라미터 설정으로 재 학습 시킴.  
grid_dtree = GridSearchCV(dt_clf, param_grid=parameters, cv=5, refit=True, return_train_score=True)

In [187]:
# 붓꽃 Train 데이터로 param_grid의 하이퍼 파라미터들을 순차적으로 학습/평가 .
grid_dtree.fit(X_train, y_train)

GridSearchCV(cv=5, error_score='raise-deprecating',
       estimator=DecisionTreeClassifier(class_weight=None, criterion='gini', max_depth=None,
            max_features=None, max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, presort=False, random_state=100,
            splitter='best'),
       fit_params=None, iid='warn', n_jobs=None,
       param_grid={'max_depth': [1, 2, 3], 'min_samples_split': [2, 3]},
       pre_dispatch='2*n_jobs', refit=True, return_train_score=True,
       scoring=None, verbose=0)

In [188]:
# 최적의 하이퍼파라미터 정보 출력
grid_dtree.best_estimator_

DecisionTreeClassifier(class_weight=None, criterion='gini', max_depth=3,
            max_features=None, max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, presort=False, random_state=100,
            splitter='best')

In [189]:
#전체적인 결과 출력
cvresult = pd.DataFrame(grid_dtree.cv_results_)
cvresult

mean_fit_time  std_fit_time  mean_score_time  std_score_time  \
0       0.000399      0.000489         0.000200        0.000400   
1       0.000000      0.000000         0.000199        0.000399   
2       0.000598      0.000489         0.000399        0.000489   
3       0.000000      0.000000         0.000200        0.000399   
4       0.000399      0.000489         0.000199        0.000399   
5       0.000599      0.000489         0.000399        0.000488   

  param_max_depth param_min_samples_split  \
0               1                       2   
1               1                       3   
2               2                       2   
3               2                       3   
4               3                       2   
5               3                       3   

                                     params  split0_test_score  \
0  {'max_depth': 1, 'min_samples_split': 2}           0.666667   
1  {'max_depth': 1, 'min_samples_split': 3}           0.666667   
2  {'max_depth': 2, 'min_samples_split': 2}           0.916667   
3  {'max_depth': 2, 'min_samples_split': 3}           0.916667   
4  {'max_depth': 3, 'min_samples_split': 2}           0.958333   
5  {'max_depth': 3, 'min_samples_split': 3}           0.958333   

   split1_test_score  split2_test_score       ...         mean_test_score  \
0           0.666667           0.666667       ...                0.666667   
1           0.666667           0.666667       ...                0.666667   
2           1.000000           0.916667       ...                0.916667   
3           1.000000           0.916667       ...                0.916667   
4           1.000000           0.916667       ...                0.966667   
5           1.000000           0.916667       ...                0.966667   

   std_test_score  rank_test_score  split0_train_score  split1_train_score  \
0        0.000000                5            0.666667            0.666667   
1        0.000000                5            0.666667            0.666667   
2        0.052705                3            0.947917            0.937500   
3        0.052705                3            0.947917            0.937500   
4        0.031180                1            0.947917            0.958333   
5        0.031180                1            0.947917            0.958333   

   split2_train_score  split3_train_score  split4_train_score  \
0            0.666667            0.666667            0.666667   
1            0.666667            0.666667            0.666667   
2            0.958333            0.958333            0.958333   
3            0.958333            0.958333            0.958333   
4            0.979167            0.979167            0.968750   
5            0.979167            0.979167            0.968750   

   mean_train_score  std_train_score  
0          0.666667         0.000000  
1          0.666667         0.000000  
2          0.952083         0.008333  
3          0.952083         0.008333  
4          0.966667         0.012148  
5          0.966667         0.012148  

[6 rows x 22 columns]

In [190]:
grid_dtree.score(X_test, y_test)

1.0