# 3강. Basic Numpy

# 이번장에서 배우는 것들
 * Numpy를 이용한 기본적 자료 구조
 * 필수적인 Numpy 동작에 대해 실습

In [1]:
#numpy를 import 시킴
import numpy as np

## 기본 자료구조 (List)

In [2]:
# python의 기본자료 구조인 list
# string 원소를 여러개 가진 list는 다음과 같이 정의 할 수 있음
week = ['mon', 'tue', 'wed', 'thu', 'fri', 'sat', 'sun']
print(week, type(week))

['mon', 'tue', 'wed', 'thu', 'fri', 'sat', 'sun'] <class 'list'>


In [3]:
# list의 특정 순서의 item을 출력하는 동작은 변수의 뒤에 []를 이용하여 접근 
# 0번째 index에 접근
print(week[0])

mon


In [4]:
# 1번째 index에 접근
print(week[1])

tue


In [5]:
# 맨뒤 접근을 -1 index로 표현함
print(week[-1])

sun


In [6]:
# 맨뒤에서 한칸 앞 index에 접근
print(week[-2])

sat


In [7]:
# integer 원소를 여러개 가진 list는 다음과 같이 정의 할 수 있음
week = [0, 1, 2, 3, 4, 5, 6]
print(week, type(week))

[0, 1, 2, 3, 4, 5, 6] <class 'list'>


In [8]:
# 여러 index에 접근
print(week[0], week[1], week[-1], week[-2])

0 1 6 5


In [9]:
# python의 list에서는 자료형에 상관없이 여러 타입을 혼합할 수 있음
week = [0, 'mon', 1.0, 2, 3, 'fri', 'sat', 6.0]
print(week, type(week))

[0, 'mon', 1.0, 2, 3, 'fri', 'sat', 6.0] <class 'list'>


In [10]:
# 여러 index에 접근
print(week[0], week[1], week[-1], week[-2])

0 mon 6.0 sat


In [11]:
# list안에 다시 list를 원소로 넣어 중첩된 list를 표현 할 수 있음
people = [ ['son', 176, 69],  ['kim', 183, 84], ['lee', 163, 57] , 7, 9]
print(people)

[['son', 176, 69], ['kim', 183, 84], ['lee', 163, 57], 7, 9]


In [12]:
# 여러 index에 접근
print(people[0], people[1], people[-1], people[-2])

['son', 176, 69] ['kim', 183, 84] 9 7


In [13]:
#list 원소는 다시 index를 주어 중첩된 list의 item에 접근 할 수 있음
print(people[0][1], people[0][-1])

176 69


In [14]:
#append 명령어로 list의 가장 끝 부분에 data를 삽입할 수 있음
people.append(['park', 177, 75])
print(people)
print(people[-1])

[['son', 176, 69], ['kim', 183, 84], ['lee', 163, 57], 7, 9, ['park', 177, 75]]
['park', 177, 75]


In [15]:
#list는 기존 item과 size가 달라도 추가 가능
people.append(['bug!', 177, 75, 234])
print(people)
print(people[-1])

[['son', 176, 69], ['kim', 183, 84], ['lee', 163, 57], 7, 9, ['park', 177, 75], ['bug!', 177, 75, 234]]
['bug!', 177, 75, 234]


In [16]:
# pop 명령어를 이용하여 list의 item을 제거 할 수 있음
# 가장 뒤의 원소를 제거함
people.pop()
print(people)

[['son', 176, 69], ['kim', 183, 84], ['lee', 163, 57], 7, 9, ['park', 177, 75]]


In [17]:
# 가장 앞의 원소를 제거함
people.pop(0)
print(people)


[['kim', 183, 84], ['lee', 163, 57], 7, 9, ['park', 177, 75]]


## 기본 자료구조 (Numpy array)

In [18]:
import numpy as np
# np array는 python list를 converting 할 수 있음
# string list를 변환
week = np.array(['mon', 'tue', 'wed', 'thu', 'fri', 'sat', 'sun'])
print(week, type(week), week.dtype)

['mon' 'tue' 'wed' 'thu' 'fri' 'sat' 'sun'] <class 'numpy.ndarray'> <U3


In [19]:
# 여러 index에 접근
print(week[0], week[1], week[-1], week[-2])

mon tue sun sat


In [20]:
# int list를 변환
week = np.array([0, 1, 2, 3, 4, 5, 6])
print(week, type(week), week.dtype)

[0 1 2 3 4 5 6] <class 'numpy.ndarray'> int32


In [21]:
# 여러 index에 접근
print(week[0], week[1], week[-1], week[-2])

0 1 6 5


In [22]:
# 복합 자료형 list는 변환할 수 없음
# 해당 자료형을 전부 포괄 할 수 있는 자료형이 있다면 해당 자료형으로 converting 후 변환
week = np.array([0, 'mon', 1.0, 2, 3, 'fri', 'sat', 6.0])
print(week, type(week), week.dtype)

['0' 'mon' '1.0' '2' '3' 'fri' 'sat' '6.0'] <class 'numpy.ndarray'> <U11


In [23]:
# 사이즈가 같은 중첩된 list는 같은 규칙에 의해 numpy array로 전환됨 
people = np.array([['son', 176, 69], ['kim', 183, 84], ['lee', 163, 57]])
print(people, type(people), people.shape)

[['son' '176' '69']
 ['kim' '183' '84']
 ['lee' '163' '57']] <class 'numpy.ndarray'> (3, 3)


In [24]:
# 사이즈가 다른 중첩된 list는 numpy array로 변환 될 수 없음
# 혀용되는 numpy array에 각 원소를 다시 list를 갖는 numpy array로 변환
people = np.array([['son', 176, 69], ['kim', 183, 84], ['lee', 163, 57], ['bug!', 183, 123, 341]])
print(people, type(people), people.shape, people.dtype)

[list(['son', 176, 69]) list(['kim', 183, 84]) list(['lee', 163, 57])
 list(['bug!', 183, 123, 341])] <class 'numpy.ndarray'> (4,) object


In [25]:
# 생성된 numpy array는 append, pop 등의 메서드가 없기 때문에 item을 새로 추가/삭제 불가능
people.

SyntaxError: invalid syntax (<ipython-input-25-9c6bb0c887a2>, line 2)

## 간단한 List와 Numpy array 연산 비교

In [26]:
a = [1,2]
b = [3,4]

print(type(a), type(b)) #<class 'list'> <class 'list'>
print(len(a), a)        # 2 [1, 2]
print(len(b), b)        # 2 [3, 4]
print(a+b)              # [1, 2, 3, 4]: appending

<class 'list'> <class 'list'>
2 [1, 2]
2 [3, 4]
[1, 2, 3, 4]


In [27]:
aa = np.array(a) # from Python List to NumPy Array
bb = np.array(b) # from Python List to NumPy Array

print(aa.dtype, bb.dtype) # int64 int64
print(type(aa), type(bb)) # int64 int64
print(len(aa), aa) # 1 [1,2]
print(len(bb), bb) # 1 [3,4]
print(aa+bb) # [4, 6]: vector operation

int32 int32
<class 'numpy.ndarray'> <class 'numpy.ndarray'>
2 [1 2]
2 [3 4]
[4 6]


## np array 구조 (shape, ndim, axis, len, size)

In [28]:
#1차원 array 선언
a1 = np.array([7,2,9,10])

#len, shape, ndim 출력
print('len', len(a1))
print('shape', a1.shape)
print('ndim', a1.ndim)
print('size', a1.size)

len 4
shape (4,)
ndim 1
size 4


In [29]:
#2차원 array 선언
a2 = np.array([[5.2, 3.0, 4.5],
               [9.1, 0.1, 0.3]])

#len, shape, ndim 출력
print('len', len(a2))
print('shape', a2.shape)
print('ndim', a2.ndim)
print('size', a2.size)

len 2
shape (2, 3)
ndim 2
size 6


In [30]:
#3차원 array 선언
a3 = np.array([
    [[1, 2], [4, 3], [7, 4]],
    [[2, 1], [9, 2], [7, 5]],
    [[1, 8], [3, 4], [0, 2]],
    [[9, 4], [6, 2], [9, 8]]])

#len, shape, ndim 출력
print('len', len(a3))
print('shape', a3.shape)
print('ndim', a3.ndim)
print('size', a3.size)

len 4
shape (4, 3, 2)
ndim 3
size 24


## np array 기본 함수

In [31]:
a = np.array([1, 2, 3, 4, 5])
#a를 전체 item 기준으로 sum과 prod 계산
print(np.sum(a)) # 15 = 1+2+3+4+5
print(np.prod(a)) # 120 = 1*2*3*4*5

15
120


In [32]:
#a를 전체 item 기준으로 평균, 분산, 표준편차 계산
print(np.mean(a)) # 3.0 = (1+2+3+4+5)/5
print(np.var(a)) # 2.0: variance
print(np.std(a)) # 1.414..: std


3.0
2.0
1.4142135623730951


In [33]:
#a를 전체 item 기준으로 최소, 최대값 계산
print(np.min(a)) # 1: minimum
print(np.max(a)) # 5: maximum

1
5


In [34]:
#a를 전체 item 기준으로 최소, 최대값의 index위치를 반환
print(np.argmin(a)) # 0: the index of the min. value
print(np.argmax(a)) # 4: the index of the max. value

0
4


In [35]:
a = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])
#a를 전체 item 기준으로 sum과 prod 계산
print(np.sum(a))
print(np.prod(a))

55
3628800


In [36]:
#axis를 바꿔가며 sum, prod 계산
print(np.sum(a), np.sum(a, axis=0), np.sum(a, axis=1))
print(np.prod(a), np.prod(a, axis=0), np.prod(a, axis=1))

55 [ 7  9 11 13 15] [15 40]
3628800 [ 6 14 24 36 50] [  120 30240]


In [37]:
#axis를 바꿔가며 mean, var, std 계산
print(np.mean(a), np.mean(a, axis=0), np.mean(a, axis=1))
print(np.var(a), np.var(a, axis=0), np.var(a, axis=1))
print(np.std(a), np.std(a, axis=0), np.std(a, axis=1))

5.5 [3.5 4.5 5.5 6.5 7.5] [3. 8.]
8.25 [6.25 6.25 6.25 6.25 6.25] [2. 2.]
2.8722813232690143 [2.5 2.5 2.5 2.5 2.5] [1.41421356 1.41421356]


In [38]:
#axis를 바꿔가며 min, max 계산
print(np.min(a), np.min(a, axis=0), np.min(a, axis=1))
print(np.max(a), np.max(a, axis=0), np.max(a, axis=1))

1 [1 2 3 4 5] [1 6]
10 [ 6  7  8  9 10] [ 5 10]


In [39]:
#axis를 바꿔가며 argmin, argmax 계산
print(np.argmin(a), np.argmin(a, axis=0), np.argmin(a, axis=1))
print(np.argmax(a), np.argmax(a, axis=0), np.argmax(a, axis=1))

0 [0 0 0 0 0] [0 0]
9 [1 1 1 1 1] [4 4]


## indexing & slicing

In [40]:
data = np.array([1, 2, 3, 4, 5, 6])
#각 원소를 index를 이용하여 출력
print(data[0], data[1])

#연속된 원소를 slice를 이용하여 출력
print(data[0:2])
print(data[1:-1])
print(data[3:])
print(data[:4])

1 2
[1 2]
[2 3 4 5]
[4 5 6]
[1 2 3 4]


In [41]:
data = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])
#각 원소를 index를 이용하여 출력
print(data[0], data[1])
print(data[0][1], data[1][2])
print(data[0, 1], data[1 ,2])

[1 2 3 4 5] [ 6  7  8  9 10]
2 8
2 8


In [42]:
#연속된 원소를 slice를 이용하여 출력
print(data[0:1])
print(data[0:2])

print(data[0:1, 3])
print(data[0:2, 3])

[[1 2 3 4 5]]
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
[4]
[4 9]


## np 산술 연산 (element-wise)

In [43]:
# shape이 같은 2개의 np array를 선언
data = np.array([1, 2])
ones = np.array([1, 1])

In [44]:
# 더하기 연산
data + ones

array([2, 3])

In [45]:
# 빼기 연산
data - ones

array([0, 1])

In [46]:
# 곱하기 연산
data * ones

array([1, 2])

In [47]:
# 나누기 연산
data / data

array([1., 1.])

## np 산술 연산 (matrix-multiplication)

In [48]:
a = np.array([[1,2],
              [3,4]])

b = np.array([[2,1],
              [4,3]])

In [49]:
# element-wise product 연산
print(a * b)

[[ 2  2]
 [12 12]]


In [50]:
# matrix-multiplication 연산
print(a @ b)

[[10  7]
 [22 15]]


In [51]:
# matrix-multiplication 연산
print(np.matmul(a, b))

[[10  7]
 [22 15]]


In [52]:
# dot-product 연산
print(np.dot(a, b))

[[10  7]
 [22 15]]


In [53]:
a = np.array([[1,2],
              [3,4],
              [5,6]
             ])

b = np.array([[2,1],
              [4,3]])

print(a.shape, b.shape)

(3, 2) (2, 2)


In [54]:
# 뒷 열과 앞 행이 같은 경우 연산 가능
print(a @ b, (a @ b).shape)

[[10  7]
 [22 15]
 [34 23]] (3, 2)


In [55]:
a = np.array([[1,2,3],
              [3,4,5],
              [5,6,7]
             ])

b = np.array([[2,1,6,2],
              [4,3,5,1],
              [1,2,1,0]
             ])

# 뒷 열과 앞 행이 같은 경우 연산 가능
print(a.shape, b.shape)
print(a @ b, (a @ b).shape)

(3, 3) (3, 4)
[[13 13 19  4]
 [27 25 43 10]
 [41 37 67 16]] (3, 4)


In [56]:
a = np.array([[1,2],
              [3,4],
              [5,6]
             ])

b = np.array([[2,1,6,2],
              [4,3,5,1],
              [1,2,1,0]
             ])

# 뒷 열과 앞 행이 다른 경우 연산 불가능
print(a.shape, b.shape)
print(a @ b, (a @ b).shape)

(3, 2) (3, 4)


ValueError: matmul: Input operand 1 has a mismatch in its core dimension 0, with gufunc signature (n?,k),(k,m?)->(n?,m?) (size 3 is different from 2)

## np Broadcasting

In [57]:
# shape이 다른 2개의 np array를 선언
data = np.array([[1, 2], [3,4]])
data2 = np.array([1, 1, 3])

In [58]:
# shape이 다른 자료는 연산 할 수 없음
data + data2

ValueError: operands could not be broadcast together with shapes (2,2) (3,) 

In [59]:
# 상수와 연산
data * 1.6

array([[1.6, 3.2],
       [4.8, 6.4]])

In [60]:
# data와 일부 shape이 같은 array로 연산
data + np.array([1,1])

array([[2, 3],
       [4, 5]])

## Transpose

In [61]:
# 2차원 np array 선언
a = np.array([[1,2,3,4]])
print(a, a.shape)

b = np.array([1,2,3,4])
print(b, b.shape)

[[1 2 3 4]] (1, 4)
[1 2 3 4] (4,)


In [62]:
# a의 transpose
print(a.T, a.T.shape)

[[1]
 [2]
 [3]
 [4]] (4, 1)


In [63]:
# 2차원 np array 선언
b = np.array([[1,2],[3,4]])
print(b, b.shape)

[[1 2]
 [3 4]] (2, 2)


In [64]:
# b의 transpose
print(b.T, b.T.shape)

[[1 3]
 [2 4]] (2, 2)


## test yourself



* $ a = [1, 2, 3], b = [4, 5, 6] $일 때 배운 np 연산을 이용하여 32를 출력해보시오.
 * 행렬연산을 이용해보시오.
 * 산술연산을 이용해보시오.

$$\begin{pmatrix} 5 & 2 & 5 \\ 1 & 7 & 4 \\ -4 & 8 & 5 \end{pmatrix}$$
* 주어진 (1) 행렬의 값을 5배 키워보시오.

* 주어진 (1) 3x3 행렬에서 axis 1와 axis 2으로 sum을 한 각각의 결과를 서로 product하여 scalar값을 출력해보시오.